version: "3.9"
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - "80:80"
    depends_on:
      - front
      - back
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/usr/src/app/src:ro
      - ./back/shared:/usr/src/app/shared:ro
    restart: unless-stopped

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/src:/svr/app/src:ro
      - ./back/test:/svr/app/test:ro
      - ./back/prisma:/svr/app/prisma:ro
      - ./back/shared:/svr/app/shared:ro
    restart: unless-stopped
    depends_on:
      - database

  migrations:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/prisma:/svr/app/prisma:ro
    env_file: ./back/.env
    command: npx prisma migrate dev --schema=./prisma/schema.prisma --skip-generate
    depends_on:
      - database

  database:
    image: bitnami/postgresql:14
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_MASTER_PORT=5432
    volumes:
      - db:/bitnami/postgresql
    ports:
      - "5432:5432"

  admin:
    image: bitnami/phppgadmin
    restart: unless-stopped
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT_NUMBER=5432
    volumes:
      - db:/bitnami/postgresql
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  db:
